ARG NODE_VERSION=20.10.0
FROM node:${NODE_VERSION}-alpine as base

WORKDIR /usr/src/app

FROM base as deps

COPY ./package.json ./package-lock.json ./
COPY ./packages/core/package.json ./packages/core/
COPY ./packages/errors/package.json ./packages/errors/
COPY ./docs/package.json ./docs/

RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY ./tsconfig*.json ./

CMD ["sh"]