ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine as base

WORKDIR /usr/src/app

FROM base as deps

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=bind,source=packages,target=packages \
    --mount=type=cache,target=/root/.npm \
    npm ci

COPY ./package*.json ./
COPY ./tsconfig*.json ./

CMD ["sh"]