name: push

on:
  push:
    branches:
      - main
  pull_request_target: 
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Install Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./packages/*/dist
  
  test:
    runs-on: ubuntu-latest
    needs: 
      - build
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ./packages

    - name: Install Dependencies
      run: npm ci
      
    - name: Test
      id: test
      run: docker compose run dev npm test
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: ./packages/*/test-report.xml
    
    - name: Test Report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: ./packages/*/test-report.xml
  
  auto-merge:
    needs:
      - build
      - lint
      - test
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.automergetoken }}
